# Site settings
title: The Technical Bits
email: oops@example.com
description: "This is where I put the technical bits."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://msteadman.github.io" # the base hostname & protocol for your site
twitter_username: MisterSteadman
github_username:  msteadman

# Build settings
markdown: kramdown
exclude: [README.md, Gemfile, Gemfile.lock]
